data:
  abc_file_name: ''
  available_charge_states: &id001 []
  parsed_data_path: /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/
  species: ''
general:
  do_abc: 0
  do_neTe: 0
  do_parse: 0
  do_plots: 1
  elemental_data_directory: ./elemental_data/
  save_to_path: /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/
  working_directory: ./
optimizer:
  Ee_hi: 0
  Ee_lo: 0
  ne_hi: 0
  ne_lo: 0
  number_of_MC: 1000
  number_of_ne: 1000
  rate_coefficient_method: ''
  rk_time_step: 0.001
parsing:
  available_charge_states: *id001
  footer: 0
  header: 0
  n_plus_file_names: []
  one_plus_file_names: []
  parsed_data_path: /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/
  raw_data_path: ''
  separator: ','
  species: ''
plotting:
  Ee_hi: 9999.0
  Ee_lo: 10.0
  F_hi: 1.0e-06
  available_charge_states:
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  confidence: 0.341
  ne_hi: 2.608e+18
  ne_lo: 100000000000.0
  plot_characteristic_time_vs_charge:
    conf_color: r
    conf_marker: o
    conf_yscale: linear
    cx_color: b
    cx_marker: ^
    cx_yscale: linear
    do_plot: 1
    inz_color: k
    inz_marker: s
    inz_yscale: linear
    output_data: true
  plot_energy_content_vs_charge:
    color: k
    do_plot: 1
    marker: s
    output_data: true
    y_hi: false
    y_lo: false
  plot_number_of_solutions_vs_F:
    do_plot: 1
    list_of_F_values:
    - 0.001
    - 0.0001
    - 1.0e-05
    - 1.0e-06
    - 1.0e-07
    - 1.0e-08
    - 1.0e-09
    y_hi: false
    y_lo: 1
  plot_solution_sets:
    do_plot: 1
    sigma: 10
    x_scale: log
    y_scale: log
  plot_triple_product_vs_charge:
    color: m
    do_plot: 1
    marker: s
    output_data: true
    y_hi: false
    y_lo: false
  solution_set_files:
  - /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/solset_MC_iters-10_N-1000_q-5.csv
  - /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/solset_MC_iters-10_N-1000_q-6.csv
  - /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/solset_MC_iters-10_N-1000_q-7.csv
  - /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/solset_MC_iters-10_N-1000_q-8.csv
  - /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/solset_MC_iters-10_N-1000_q-9.csv
  - /home/miha/Work/codes/Consecutive_Transients_Analyzer/test/guiTestResults/solset_MC_iters-10_N-1000_q-10.csv
