#!/bin/bash        
#SBATCH -J mytest        ### job name is "mytest"
#SBATCH -o out           ## output to file "out" in the working directory
#SBATCH -e errorout      ## error message output 
###SBATCH -n 24            ## parallel job, reserve 4 cores, same as --ntasks=4
#SBATCH -N 1             ## reserve one node (24 cores), same as   --nodes=1 
#SBATCH --time=30:00     ## optional; jobs takes max 30 minutes (it will be killed if it's not finished in 30 minutes)
###SBATCH --cpus-per-task=24 

module load ASE/3.18.0-foss-2018b-Python-3.6.6

srun python3 /n/work01/misapema/ppp/popTauPy/opt_neTe.py
